services:
  - type: web
    name: cave-escape
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER_EXTERNAL_URL
        value: cave-escape.onrender.com
